version: "3.3"

services:

  sutom:
    image: chleo/sutom:latest
    ports:
      - 3000:3000
  score:
    image: chleo/score:latest
    ports:
      - 5000:5000
    volumes:
      - storageScore:/SCORE/storage
  login:
    image: chleo/login:latest
    ports:
      - 8000:8000
    volumes:
      - storageLogin:/LOGIN/storage

volumes:
  storageScore:
  storageLogin: